Выполнил 4 лабу
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-DakEnviy pull request #1
Opened 2020-03-08 23:23 UTC by DakEnviy

2020-03-19 12:52 UTC, hey-its-sasha requested changes
за женерики +

про коммит месседжи: пиши их продолжением фразы "If applied, this commit will", то есть они тогда будут "add complete hash table implementation" или "fix PR comments". ну и отвыкай от кириллицы :)

2020-03-19 12:52 UTC, hey-its-sasha commented on src/main/java/ru/itmo/java/HashTable.java
> +public final class HashTable<K, V> {
почему написал final?

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static int hash(final Object key) {
где узнал про то, чтобы писать final у входных параметров? просто интересно

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    public HashTable(int initialCapacity, final float loadFactor) {
на самом деле менять входные параметры -- моветон. лучше заводить новые переменные

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static int hash(final Object key) {
зачем он статический?

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int findIndex(final int hash, final K key) {
можно принимать только ключ, и уже внутри метода считать хэш, чтобы не делать этого не вызывающей стороне

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        @SuppressWarnings("unchecked")
зачем?

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        private V value;
можно было сделать всю Entry immutable

2020-03-19 12:52 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        private final int hash;
в жаве любят геттеры, доступ к проперти напрямую это больше про котлин

2020-03-19 20:20 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +public final class HashTable<K, V> {
Чтобы не наследовались лишний раз. Просто не вижу смысла в расширении данного класса.

2020-03-19 20:21 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static int hash(final Object key) {
Не знаю, где именно узнал. Опыт, привычка

2020-03-19 20:22 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +    public HashTable(int initialCapacity, final float loadFactor) {
Конкретно в этом случае это приводит к лишнему коду. Если язык позволяет безболезненно менять и это не ухудшает читаемость, то why not?

2020-03-19 20:25 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static int hash(final Object key) {
Ну я в этом методе не использую класс, да и быстрее работает из-за раннего связывания

2020-03-19 20:28 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +        @SuppressWarnings("unchecked")
Entry не задженерить, так что там появляется `Unchecked assignment`

2020-03-19 20:29 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +        private V value;
Тогда дольше будет работать `put` на существующем ключе. Сделал так, чтобы отказаться от создания нового `Entry` при каждому вызове `put`

2020-03-19 20:29 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +        private final int hash;
Это да, но кажется, что тут это будет уместно и удобно

2020-03-19 20:31 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int findIndex(final int hash, final K key) {
Тогда придется по 2 раза хэш считать, ибо мне нужен доступ к значению хэша на вызывающей стороне

2020-03-19 20:35 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +        @SuppressWarnings("unchecked")
Точнее массив `Entry`

2020-03-19 20:42 UTC, DakEnviy commented on src/main/java/ru/itmo/java/HashTable.java
> +    public HashTable(int initialCapacity, final float loadFactor) {
Так, беру свои слова назад, без изменения даже изящнее вышло))

2020-03-21 11:59 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +public final class HashTable<K, V> {
👍

2020-03-21 12:00 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static int hash(final Object key) {
👍

2020-03-21 12:05 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static int hash(final Object key) {
ага, просто тут кто как делает, кто-то спамит final везде (раньше так делал), кто-то его везде выпиливает, чтоб лучше читалось

2020-03-21 12:06 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int findIndex(final int hash, final K key) {
это да, но думаю там потери вообще не будут ощущаться, учитывая на каком языке ты пишешь :)

2020-03-21 12:08 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        private V value;
вряд ли сильно дольше, но да

2020-03-21 12:10 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        private final int hash;
удобнее 100%, но в этом курсе цель писать на жаве по её канонам (хоть каким-то), поэтому я снижаю баллы за такие штуки, чтобы писали геттеры. поэтому писать или нет это всегда твой выбор :)

2020-03-21 12:16 UTC, hey-its-sasha approved these changes

2020-03-21 13:01 UTC, merged